# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJn1rle9YLE2a6BKFPR5sL_DVmmYeUIk
"""

#clases con el profe Erick 1
cuenta = int(input("total de la cuenta: $"))
propina =cuenta *0.10
print ("propina: $",propina)
print ("total a pagar mas propina: $",cuenta + propina)

contra=input("ingresa una contraseña: ")
mayus= False
num=False
for i in contra:
  if i.isupper():
    mayus=True
  if i.isdigit():
    num=True
if len (contra)>7 and mayus and num :
 print ("contra segura")
else:
  print ("contraseña insegura")

impuesto = int(input("ingresa tu consumo de energia electrica: "))
if impuesto < 101:
  print("el impuesto que tenes que pagar es $0.00")
elif impuesto >= 101 and impuesto<200:
  pagoplus=impuesto*0.5
  print("el impuesto que tenes que pagar es: $", pagoplus)
elif impuesto >= 201:
  pagoplus=impuesto*0.7
  print("el impuesto que tenes que pagar es: $", pagoplus)

magico=int(input("ingresa un numero"))
if magico %7 ==0 and magico %5 >0:
  print("el numero es magico")
else:
  print("el numero no es magico")

